replace display1 to headline4
madhukesh048/Flutter-MVVM-VS-Code-extension-Pack pull request #11
Opened 2020-05-13 16:11 UTC by lcsvcn

Replacement due to warning below:

> 'display1' is deprecated and shouldn't be used. This is the term used in the 2014 version of material design. The modern term is headline4. This feature was deprecated after v1.13.8..
> Try replacing the use of the deprecated member with the replacement.

2020-06-05 18:15 UTC, lcsvcn commented
Changelog list:
- update all dependencies
- display1(DEPRECATED) to headline4
- provider_architecture (DEPRECATED) to stacked
- viewModel(DEPRECATED) to viewModelBuilder 
- change mobile from black to green

2020-06-05 18:17 UTC, lcsvcn commented
@madhukesh048 

Can you do a code review and update the published visual code extension?

I am using it in all my projects and these deprecated are making me do a lot of manual unnecessary work

2020-06-06 06:17 UTC, ChangJoo-Park commented
:+1:

2020-06-06 06:17 UTC, ChangJoo-Park approved these changes

2020-06-06 06:29 UTC, ChangJoo-Park commented
@lcsvcn Please change `SingleChildCloneableWidget` to `SingleChildWidget` ?

If you update provider up to ^4, must change it.

2020-06-06 06:30 UTC, ChangJoo-Park requested changes
[**@lcsvcn**](https://github.com/lcsvcn) Please change `SingleChildCloneableWidget` to `SingleChildWidget` ?

If you update provider up to ^4, must change it.

2020-06-06 10:09 UTC, ajilo297 commented
Thanks for the PR. I will be looking into how feasible this is.

2020-06-08 11:53 UTC, lcsvcn commented
@ChangJoo-Park Thanks for review my code, I have forgotten to replace this method.

@ajilo297 Thanks, hoping to see it in a next release. :)

2020-06-08 16:46 UTC, ajilo297 commented
@lcsvcn Hey. I am quite happy with the PR and it looks as if everything is still functional. But I don't want to merge it yet. The problem is that there are quite a few users who are still using this extension and have not migrated yet to Stacked. I am concerned that it might break things for them.

A possible resolution would be to somehow add a few more input actions that let the user select the versions of the dependencies involved. I will still need a few more days to consider the options we have to make the migration without breaking the extensions for existing users.

I am open to any suggestions you have. :-)

2020-06-08 18:13 UTC, lcsvcn commented
Well, I understand you concern.

The easiest way to avoid breaking up the code would be to add a "legacy" checkbox (which will be disable by default) and will load the current code if it is enable. If it is disable, it will load the version compatible with the latest versions of pub library, at moment this in this PR.

A more robust way to fix this, is to add a field for every library that this project depend and user will need to add manually or it fetch automatically from pubspec.yaml at the current project (I do not know if this is possible and how can be done)

What I think, people should keep their library in the latest version, for security and stability increase for their app. So I think we should go with the first and easiest version, that will allow old users of the extension to have support and new users will be encouraged to start using the newest library. Otherwise we might have a fragmentation of users and possible different errors for different configurations.

2022-05-13 03:30 UTC, closed without merging